services:
  model-training:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/src/data
      - ./models:/app/src/models
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN
    command: ["python", "train.py", "local-dev"]

  model-tests:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/src/data
      - ./models:/app/src/models
    environment:
      - PYTHONPATH=/app/src
      - HF_TOKEN
    working_dir: /app
    command: ["python", "-m", "pytest", "/app/tests", "-v"]