stages:
  get_data:
    cmd: python src/download_data.py 
    deps:
      - src/download_data.py
    outs:
      - data/raw/raw_data.tsv
  test_data:
    cmd: pytest tests/test_data.py
    deps:
      - data/raw/raw_data.tsv
      - tests/test_data.py
  prepare:
    cmd: python src/preprocess.py data/raw/raw_data.tsv
    deps:
      - data/raw/raw_data.tsv
      - src/preprocess.py
    outs:
      - data/splits/X_train.npy
      - data/splits/X_test.npy
      - data/splits/y_train.npy
      - data/splits/y_test.npy
  train:
    cmd: python src/train.py local-dev
    deps:
      - data/splits/X_train.npy
      - data/splits/y_train.npy
      - data/splits/X_test.npy
      - data/splits/y_test.npy
      - src/train.py
    outs:
      - models/sentiment_classifier.joblib
  evaluate:
    cmd: python src/evaluate.py models/sentiment_classifier.joblib data/splits/X_test.npy data/splits/y_test.npy
    deps:
      - models/sentiment_classifier.joblib
      - data/splits/X_test.npy
      - data/splits/y_test.npy
      - src/evaluate.py
    metrics:
      - metrics/metrics.json