stages:
  prepare:
    cmd: python src/download_data.py data/raw/train_data.tsv data/processed/train_data_processed.tsv
    deps:
      - src/download_data.py
    outs:
      - data/processed/train_data_processed.tsv
  train:
    cmd: python src/run_train.py data/processed/train_data_processed.tsv models/sentiment_classifier.joblib
    deps:
      - data/processed/train_data_processed.tsv
      - src/run_train.py
      - src/train.py
    outs:
      - models/sentiment_classifier.joblib
  evaluate:
    cmd: python src/evaluate.py models/sentiment_classifier.joblib data/processed/train_data_processed.tsv metrics/metrics.json
    deps:
      - models/sentiment_classifier.joblib
      - data/processed/train_data_processed.tsv
      - src/evaluate.py
    metrics:
      - metrics/metrics.json